---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Delaer Portal:
    - Dev:
        href: https://dealer.chektdev.com/
    - QE:
        href: https://dealer.chektqe.com/
    - Prod:
        href: https://dealer.chekt.com/
        siteMonitor: https://dealer.chekt.com/

- Monitoring Portal:
    - Dev:
        href: https://monitoring.chektdev.com/
    - QE:
        href: https://monitoring.chektqe.com/
    - Prod:
        href: https://monitoring.chekt.com/

- End User Web:
    - Dev:
        href: https://app.chektdev.com/
    - QE:
        href: https://app.chektqe.com/
    - Prod:
        href: https://app.chekt.com/

- Tools:
    - GitHub:
        icon: /icons/github.svg
        href: https://github.com/chekt
    - Jira:
        icon: /icons/jira.svg
        href: https://alarmcom.atlassian.net/jira/software/c/projects/CHEKT/boards/232?quickFilter=529
    - Codefresh:
        icon: /icons/codefresh.png
        href: https://g.codefresh.io
    - Keycloak:
        icon: /icons/keycloak.svg
        href: https://keycloak.chektdev.com
    - Status:
        icon: /icons/status.png
        href: https://status.chekt.com