---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: CHeKT Homepage
description: A description of my awesome homepage
startUrl: /
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
favicon: /favicon.ico
theme: dark
color: blue
disableCollapse: true

blockHighlights:
  levels:
    good: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"
    warn: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

layout:
  Delaer Portal:
    tab: First
    style: row
    columns: 3
    levels:
      good: "bg-emerald-500/40 text-emerald-950 dark:bg-emerald-900/60 dark:text-emerald-400"
      warn: "bg-amber-300/30 text-amber-900 dark:bg-amber-900/30 dark:text-amber-200"
      danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

  Monitoring Portal:
    tab: First
    style: row
    columns: 3
  End User Web:
    tab: Second
    style: row
    columns: 3
  Tools:
    style: row
    columns: 2

  Grafana:
    iconsOnly: true
headerStyle: clean
quicklaunch:
  searchDescriptions: false
  hideInternetSearch: true
  showSearchSuggestions: false
  hideVisitURL: true
  provider: ""

hideVersion: true
disableUpdateCheck: true
disableIndexing: true