---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: CHeKT Homepage
description: A description of my awesome homepage
startUrl: /
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
favicon: /favicon.ico
theme: dark
color: blue
disableCollapse: true

blockHighlights:
  levels:
    good: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"
    warn: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"
    danger: "bg-rose-700/45 text-rose-200 dark:bg-rose-950/70 dark:text-rose-400"

layout:
  Dealer Portal:
    style: row
    columns: 4
  Monitoring Portal:
    style: row
    columns: 4
  End User Web:
    style: row
    columns: 4
  Console:
    style: row
    columns: 4

  Tools:
    style: row
    columns: 4

  Tools(By Env):
    style: row
    columns: 2

    header: false
    Kibana:
      style: row
      columns: 3
    Grafana:
      style: row
      columns: 3
    GitOps:
      style: row
      columns: 3

headerStyle: clean
quicklaunch:
  searchDescriptions: false
  hideInternetSearch: true
  showSearchSuggestions: false
  hideVisitURL: true
  provider: ""

hideVersion: true
disableUpdateCheck: true
disableIndexing: true