---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
    icon: /icons/chekt.png
- greeting:
    text_size: xl
    text: The door to the Central Station

